import { RESOURCE_MODELS, TEST_MODELS } from './resources.ts';
import { UNIT_MODELS } from './units.ts';
import { BUILDING_MODELS } from './buildings.ts';
import { WALL_MODELS } from './walls.ts';
import { SIEGE_MODELS } from './siege.ts';
import { SHIP_MODELS } from './ships.ts';
import { INFANTRY_MODELS } from './infantry.ts';
import { MOUNTED_MODELS } from './mounted.ts';
import { PRIEST_MODELS } from './priest.ts';
import { WONDER_MODELS } from './wonder.ts';
import { ANIMAL_MODELS } from './animals.ts';
import { SOLDIER_MODELS } from './soldiers.ts';
import { CAVALRY_MODELS } from './cavalry.ts';
import { setModels } from './arch/kit.ts';
import { EGYPTIAN } from './arch/egyptian.ts';
import { BABYLONIAN } from './arch/babylonian.ts';
import type { ModelDef } from './types.ts';

export const MODELS: ModelDef[] = [...TEST_MODELS, ...RESOURCE_MODELS, ...UNIT_MODELS, ...SOLDIER_MODELS, ...CAVALRY_MODELS, ...ANIMAL_MODELS, ...BUILDING_MODELS, ...WALL_MODELS, ...SIEGE_MODELS, ...INFANTRY_MODELS, ...MOUNTED_MODELS, ...PRIEST_MODELS, ...WONDER_MODELS, ...SHIP_MODELS, ...setModels(EGYPTIAN), ...setModels(BABYLONIAN)];
export const MODEL_BY_ID = new Map(MODELS.map((m) => [m.id, m]));
export type { ModelDef, ClipDef } from './types.ts';
