/**
 * Generates src/sim/math/trigTable.ts: sin values for 1024 steps around the circle as decimal literals, so the
 * simulation never calls Math.sin (implementation-defined across JS engines — DECISIONS D1). Decimal literals parse
 * identically everywhere. Run: node tools/gen-trig-table.ts
 */
import { writeFileSync } from 'node:fs';

const N = 1024;
const vals: string[] = [];
for (let i = 0; i < N; i++) {
  const v = Math.sin((2 * Math.PI * i) / N);
  vals.push(Math.abs(v) < 1e-15 ? '0' : v.toFixed(15).replace(/0+$/, '').replace(/\.$/, ''));
}
const lines: string[] = [];
for (let i = 0; i < N; i += 8) lines.push('  ' + vals.slice(i, i + 8).join(', ') + ',');
const src = `// GENERATED by tools/gen-trig-table.ts — do not edit.
/** sin(2π·i/${N}) for i in [0, ${N}), as decimal literals (engine-independent). */
export const SIN_TABLE: readonly number[] = [
${lines.join('\n')}
];
export const TRIG_STEPS = ${N};
`;
writeFileSync(new URL('../src/sim/math/trigTable.ts', import.meta.url), src);
console.log(`wrote ${N} entries`);
